# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63748d8f00869b73613d7f0737f3138576784ada71ca4a1f0427000a77bbf83289b5fd5dc7f738ad6e3bd1c9a38edc81a741b6616e2332ea10ebf1984c436fe6

test:
  secret_key_base: 2d2bad287a49c7dbcd8dadff753fe7b5a084b45c0124fbd405a25e1576d7fb31eb373c142f891a32b43e05fa6730cd68935a51c024d61756f87263d043876345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
